name: flutter_feedback_kit
description: "A Flutter package for collecting in-app user feedback with customizable widgets and pluggable backends (webhook, email, Firebase, etc.)."
version: 0.1.0
homepage: https://github.com/SkyWalker2506/flutter_feedback_kit

topics:
  - feedback
  - user-feedback
  - widget
  - utility

environment:
  sdk: ^3.11.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.5.5
  connectivity_plus: ^7.0.0
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
