// Generated by mason — flutter_feedback_kit brick
// Backend: {{backend}}
// AI categorization: {{use_ai_categorization}}
//
// 1. Add the required dependencies to pubspec.yaml:
//
//    dependencies:
//      flutter_feedback_kit: ^0.1.0
{{#webhook}}
//      # No additional package needed for webhook backend.
{{/webhook}}
{{#firebase}}
//      flutter_feedback_kit_firebase: ^0.1.0
{{/firebase}}
{{#linear}}
//      flutter_feedback_kit_linear: ^0.1.0
{{/linear}}
{{#use_ai_categorization}}
//      # AiCategorizationMiddleware is part of flutter_feedback_kit.
{{/use_ai_categorization}}
//
// 2. Drop the floatingActionButton from HomeScreen into your own Scaffold.

import 'package:flutter/material.dart';
import 'package:flutter_feedback_kit/flutter_feedback_kit.dart';
{{#firebase}}
import 'package:flutter_feedback_kit_firebase/flutter_feedback_kit_firebase.dart';
{{/firebase}}
{{#linear}}
import 'package:flutter_feedback_kit_linear/flutter_feedback_kit_linear.dart';
{{/linear}}

// ---------------------------------------------------------------------------
// Backend factory
// ---------------------------------------------------------------------------

/// Returns the configured [FeedbackBackend].
///
/// Call [backend.dispose()] when the owning widget is disposed.
FeedbackBackend createFeedbackBackend() {
{{#webhook}}
  return WebhookBackend(
    url: '{{webhook_url}}',
  );
{{/webhook}}
{{#firebase}}
  // Ensure Firebase.initializeApp() has been called before using this backend.
  return FirebaseFeedbackBackend(
    collection: 'feedback',
    // screenshotsBucket: 'feedback-screenshots', // uncomment to upload screenshots to Storage
  );
{{/firebase}}
{{#linear}}
  return LinearFeedbackBackend(
    // apiKey: 'YOUR_LINEAR_API_KEY', // load from remote config — never hard-code
    // teamId: 'YOUR_TEAM_ID',
  );
{{/linear}}
}

// ---------------------------------------------------------------------------
// Middleware list
// ---------------------------------------------------------------------------

{{#use_ai_categorization}}
/// Middleware pipeline — [AiCategorizationMiddleware] auto-suggests a category
/// using Claude. Pass the Anthropic API key via --dart-define or load it from
/// remote config at runtime. Never embed the key in source.
List<FeedbackMiddleware> createMiddlewares() {
  return [
    AiCategorizationMiddleware(
      apiKey: const String.fromEnvironment('ANTHROPIC_API_KEY'),
    ),
  ];
}
{{/use_ai_categorization}}
{{^use_ai_categorization}}
/// Returns an empty middleware list.
///
/// Add [AiCategorizationMiddleware] or a custom [FeedbackMiddleware] here.
List<FeedbackMiddleware> createMiddlewares() => const [];
{{/use_ai_categorization}}

// ---------------------------------------------------------------------------
// Example widget
// ---------------------------------------------------------------------------

/// Drop this into your app and replace the body with your own content.
class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  late final FeedbackBackend _backend;

  @override
  void initState() {
    super.initState();
    _backend = createFeedbackBackend();
  }

  @override
  void dispose() {
    _backend.dispose();
    super.dispose();
  }

{{#use_ai_categorization}}
  // FeedbackWidget is used directly so middlewares can be supplied.
  Future<void> _openFeedback() async {
    await showModalBottomSheet<void>(
      context: context,
      isScrollControlled: true,
      builder: (_) => Padding(
        padding: EdgeInsets.fromLTRB(
          16,
          16,
          16,
          MediaQuery.of(context).viewInsets.bottom + 16,
        ),
        child: FeedbackWidget(
          backend: _backend,
          appVersion: '{{app_version}}',
          metadataCollector: FeedbackMetadataCollector(),
          middlewares: createMiddlewares(),
          showRating: true,
          onSuccess: () {
            Navigator.pop(context);
            debugPrint('[FeedbackKit] Submitted');
          },
          onError: (e) => debugPrint('[FeedbackKit] Error: $e'),
        ),
      ),
    );
  }
{{/use_ai_categorization}}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('My App')),
      body: const Center(child: Text('Your app content here')),
{{#use_ai_categorization}}
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _openFeedback,
        icon: const Icon(Icons.feedback_outlined),
        label: const Text('Feedback'),
      ),
{{/use_ai_categorization}}
{{^use_ai_categorization}}
      floatingActionButton: FeedbackButton(
        backend: _backend,
        appVersion: '{{app_version}}',
        metadataCollector: FeedbackMetadataCollector(),
        showRating: true,
        onSuccess: () => debugPrint('[FeedbackKit] Submitted'),
        onError: (e) => debugPrint('[FeedbackKit] Error: $e'),
      ),
{{/use_ai_categorization}}
    );
  }
}
